spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: never

  mail:
    host: smtp.sendgrid.net
    port: 2525
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  mail:
    from: ${MAIL_FROM}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:28800000}

frontend:
  url: ${FRONTEND_URL}